### PR TITLE
Update 12-widget-reference.markdown

### PR DESCRIPTION
**Pull request by corbinmurakami**

### CODE REVIEW

**Review by corbinmurakami — COMMENTED** [review]
Big improvement, Neal. Thanks for those changes.
1. There's one reference to a portlet under shipments--do we still reference portlets?
2. Sort order: alphabetical? Group into 2-3 groupings so certain widget names stay close to each other?
3. Time to add links out to related docs more consistently.

**Comment by nealrobbins** [comment]
1. @corbinmurakami Yes, we still use portlets. In this case, I'm referring to the shipments app that is only accessible from the site menu--it isn't a widget because it can't be drag-and-dropped onto a page. (Of course, I could be mistaken that that particular app in fact uses portlet technology. But I believe it does).

2. I find it difficult to group our widgets into categories--every time I try I end up either putting most of  them into a single category, or ending up with several in categories by themselves. What I've done is alphabetical order, with one or two exceptions: for instance I put the Mini Cart in with the other cart widgets.

3. I can't put in accurate links yet because I don't know where this will be published. My understanding is that @sez11a followed up with you and Milen on that earlier this week.

All your changes look great to me.

**Comment by corbinmurakami** [comment]
1. K thanks, just wanted to confirm.
2. Okay, that works for me.
3. K, so the plan is to circle back to this? I'm good with that as long as there's a reliable method of making sure it happens. And I don't remember talking to Rich about that this week.

**Comment by sez11a** [comment]
@nealrobbins There's nothing preventing you from putting links in. Just do them the way you've been doing them. @corbinmurakami I have a URL that I think @milendyankov sent you; he's waiting for your response.

**Pull request merged**
